services:
  accounts-gateway:
    command: npm start accounts-gateway
    container_name: accounts-gateway
    environment:
      - ACCOUNTS_GATEWAY_HOST=${ACCOUNTS_GATEWAY_HOST}
      - ACCOUNTS_GATEWAY_PORT=${ACCOUNTS_GATEWAY_PORT}
      - GLOBAL_PREFIX=${GLOBAL_PREFIX}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - THROTTLE_LIMIT=${THROTTLE_LIMIT}
      - THROTTLE_TTL=${THROTTLE_TTL}
    image: node:${NODE_VERSION}
    ports:
      - ${ACCOUNTS_GATEWAY_PORT}:${ACCOUNTS_GATEWAY_PORT}
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
  accounts-service:
    command: npm start accounts-service
    container_name: accounts-service
    environment:
      - ACCOUNTS_DB_NAME=${ACCOUNTS_DB_NAME}
      - ACCOUNTS_SERVICE_HOST=${ACCOUNTS_SERVICE_HOST}
      - ACCOUNTS_SERVICE_PORT=${ACCOUNTS_SERVICE_PORT}
      - CONTACT_RECIPIENT_EMAIL=${CONTACT_RECIPIENT_EMAIL}
      - CONTACT_RECIPIENT_NAME=${CONTACT_RECIPIENT_NAME}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - SEND_IN_BLUE_API_KEY=${SEND_IN_BLUE_API_KEY}
      - THROTTLE_LIMIT=${THROTTLE_LIMIT}
      - THROTTLE_TTL=${THROTTLE_TTL}
    image: node:${NODE_VERSION}
    ports:
      - ${ACCOUNTS_SERVICE_PORT}:${ACCOUNTS_SERVICE_PORT}
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
  accounts-web:
    command: npm start accounts-web
    container_name: accounts-web
    image: node:${NODE_VERSION}
    ports:
      - ${ACCOUNTS_WEB_PORT}:${ACCOUNTS_WEB_PORT}
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
  elasticsearch:
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    image: elasticsearch:${ELK_VERSION}
    ports:
      - ${ELASTICSEARCH_PORT_HTTP}:${ELASTICSEARCH_PORT_HTTP}
      - ${ELASTICSEARCH_PORT_TCP}:${ELASTICSEARCH_PORT_TCP}
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
      - ./config/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  kibana:
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT_HTTP}
    image: kibana:${ELK_VERSION}
    ports:
      - ${KIBANA_PORT}:${KIBANA_PORT}
  logstash:
    container_name: logstash
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT_HTTP}
    image: logstash:${ELK_VERSION}
    ports:
      - ${LOGSTASH_PORT_BEATS}:${LOGSTASH_PORT_BEATS}
      - ${LOGSTASH_PORT_TCP}:${LOGSTASH_PORT_TCP}
      - ${LOGSTASH_PORT_MONITORING}:${LOGSTASH_PORT_MONITORING}
    volumes:
      - ./config/logstash/config/log4j2.properties:/usr/share/logstash/config/log4j2.properties
      - ./config/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./config/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
  mongo:
    container_name: mongo
    image: mongo:${MONGO_VERSION}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongo:/data/db
  portfolio-gateway:
    command: npm start portfolio-gateway
    container_name: portfolio-gateway
    environment:
      - GLOBAL_PREFIX=${GLOBAL_PREFIX}
      - PORTFOLIO_GATEWAY_HOST=${PORTFOLIO_GATEWAY_HOST}
      - PORTFOLIO_GATEWAY_PORT=${PORTFOLIO_GATEWAY_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - THROTTLE_LIMIT=${THROTTLE_LIMIT}
      - THROTTLE_TTL=${THROTTLE_TTL}
    image: node:${NODE_VERSION}
    ports:
      - ${PORTFOLIO_GATEWAY_PORT}:${PORTFOLIO_GATEWAY_PORT}
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
  portfolio-service:
    command: npm start portfolio-service
    container_name: portfolio-service
    environment:
      - CONTACT_RECIPIENT_EMAIL=${CONTACT_RECIPIENT_EMAIL}
      - CONTACT_RECIPIENT_NAME=${CONTACT_RECIPIENT_NAME}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - PORTFOLIO_DB_NAME=${PORTFOLIO_DB_NAME}
      - PORTFOLIO_SERVICE_HOST=${PORTFOLIO_SERVICE_HOST}
      - PORTFOLIO_SERVICE_PORT=${PORTFOLIO_SERVICE_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - SEND_IN_BLUE_API_KEY=${SEND_IN_BLUE_API_KEY}
      - THROTTLE_LIMIT=${THROTTLE_LIMIT}
      - THROTTLE_TTL=${THROTTLE_TTL}
    image: node:${NODE_VERSION}
    ports:
      - ${PORTFOLIO_SERVICE_PORT}:${PORTFOLIO_SERVICE_PORT}
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
  portfolio-web:
    command: npm start portfolio-web
    container_name: portfolio-web
    image: node:${NODE_VERSION}
    ports:
      - ${PORTFOLIO_WEB_PORT}:${PORTFOLIO_WEB_PORT}
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
  redis:
    command: redis-server --appendonly yes
    container_name: redis
    image: redis:${REDIS_VERSION}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis:/data
version: '3.9'
volumes:
  elasticsearch:
  mongo:
  redis:
