services:
  accounts-gateway:
    command: npm start accounts-gateway
    build:
      args:
        - NODE_VERSION=${NODE_VERSION}
        - PORT=${ACCOUNTS_GATEWAY_PORT}
      context: .
    container_name: accounts-gateway
    image: node
    ports:
      - ${ACCOUNTS_GATEWAY_PORT}:${ACCOUNTS_GATEWAY_PORT}
    volumes:
      - ./apps/accounts-gateway:/usr/src/app/apps/accounts-gateway
      - /usr/src/app/node_modules
  accounts-service:
    command: npm start accounts-service
    build:
      args:
        - NODE_VERSION=${NODE_VERSION}
        - PORT=${ACCOUNTS_SERVICE_PORT}
      context: .
    container_name: accounts-service
    image: node
    ports:
      - ${ACCOUNTS_SERVICE_PORT}:${ACCOUNTS_SERVICE_PORT}
    volumes:
      - ./apps/accounts-service:/usr/src/app/apps/accounts-service
      - /usr/src/app/node_modules
  accounts-web:
    command: npm start accounts-web
    build:
      args:
        - NODE_VERSION=${NODE_VERSION}
        - PORT=${ACCOUNTS_WEB_PORT}
      context: .
    container_name: accounts-web
    image: node
    ports:
      - ${ACCOUNTS_WEB_PORT}:${ACCOUNTS_WEB_PORT}
    volumes:
      - ./apps/accounts-web:/usr/src/app/apps/accounts-web
      - /usr/src/app/node_modules
  elasticsearch:
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    image: elasticsearch:${ELK_VERSION}
    ports:
      - ${ELASTICSEARCH_PORT_HTTP}:${ELASTICSEARCH_PORT_HTTP}
      - ${ELASTICSEARCH_PORT_TCP}:${ELASTICSEARCH_PORT_TCP}
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
      - ./config/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  kibana:
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT_HTTP}
    image: kibana:${ELK_VERSION}
    ports:
      - ${KIBANA_PORT}:${KIBANA_PORT}
  logstash:
    container_name: logstash
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT_HTTP}
    image: logstash:${ELK_VERSION}
    ports:
      - ${LOGSTASH_PORT_BEATS}:${LOGSTASH_PORT_BEATS}
      - ${LOGSTASH_PORT_TCP}:${LOGSTASH_PORT_TCP}
      - ${LOGSTASH_PORT_MONITORING}:${LOGSTASH_PORT_MONITORING}
    volumes:
      - ./config/logstash/config/log4j2.properties:/usr/share/logstash/config/log4j2.properties
      - ./config/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./config/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
  mongo:
    container_name: mongo
    image: mongo:${MONGO_VERSION}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongo:/data/db
  portfolio-gateway:
    command: npm start portfolio-gateway
    build:
      args:
        - NODE_VERSION=${NODE_VERSION}
        - PORT=${PORTFOLIO_GATEWAY_PORT}
      context: .
    container_name: portfolio-gateway
    image: node
    ports:
      - ${PORTFOLIO_GATEWAY_PORT}:${PORTFOLIO_GATEWAY_PORT}
    volumes:
      - ./apps/portfolio-gateway:/usr/src/app/apps/portfolio-gateway
      - /usr/src/app/node_modules
  portfolio-service:
    command: npm start portfolio-service
    build:
      args:
        - NODE_VERSION=${NODE_VERSION}
        - PORT=${PORTFOLIO_SERVICE_PORT}
      context: .
    container_name: portfolio-service
    image: node
    ports:
      - ${PORTFOLIO_SERVICE_PORT}:${PORTFOLIO_SERVICE_PORT}
    volumes:
      - ./apps/portfolio-service:/usr/src/app/apps/portfolio-service
      - /usr/src/app/node_modules
  portfolio-web:
    command: npm start portfolio-web
    build:
      args:
        - NODE_VERSION=${NODE_VERSION}
        - PORT=${PORTFOLIO_WEB_PORT}
      context: .
    container_name: portfolio-web
    image: node
    ports:
      - ${PORTFOLIO_WEB_PORT}:${PORTFOLIO_WEB_PORT}
    volumes:
      - ./apps/portfolio-web:/usr/src/app/apps/portfolio-web
      - /usr/src/app/node_modules
  redis:
    command: redis-server --appendonly yes
    container_name: redis
    image: redis:${REDIS_VERSION}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis:/data
version: '3.9'
volumes:
  elasticsearch:
  mongo:
  redis:
