networks:
  ah_network:
    driver: bridge
services:
  adminer:
    container_name: adminer
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - ADMINER_DEFAULT_SERVER=${ADMINER_DEFAULT_SERVER}
    healthcheck:
      interval: 30s
      retries: 3
      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
      timeout: 10s
    image: adminer:${ADMINER_VERSION}
    networks:
      - ah_network
    ports:
      - ${ADMINER_PORT}:8080
    restart: unless-stopped
