networks:
  ah_network:
    driver: bridge
services:
  nginx:
    container_name: nginx
    env_file:
      - .env
    healthcheck:
      interval: 30s
      retries: 3
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      timeout: 10s
    image: nginx:${NGINX_VERSION}
    networks:
      - ah_network
    ports:
      - ${NGINX_PORT}:8080
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
