networks:
  ah_network:
    driver: bridge
services:
  redis:
    container_name: redis
    env_file:
      - .env
    healthcheck:
      interval: 30s
      retries: 3
      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
      timeout: 10s
    image: redis:${REDIS_VERSION}
    networks:
      - ah_network
    ports:
      - ${REDIS_PORT}:8080
    restart: unless-stopped
    volumes:
      - redis_data:/usr/share/elasticsearch/data
volumes:
  redis_data:
    driver: local
