import type { Metadata } from "next";
import { JSX, ReactNode } from "react";

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

type RootLayoutProps = {
  children: ReactNode;
};

export default function RootLayout({
  children,
}: Readonly<RootLayoutProps>): JSX.Element {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
