networks:
  ah_network:
    driver: bridge
services:
  redis-commander:
    container_name: redis-commander
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env
    healthcheck:
      interval: 30s
      retries: 3
      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
      timeout: 10s
    image: redis-commander:${REDIS_COMMANDER_VERSION}
    networks:
      - ah_network
    ports:
      - ${REDIS_COMMANDER_PORT}:8080
    restart: unless-stopped
