networks:
  ah_network:
    driver: bridge
services:
  wordpress:
    container_name: wordpress
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
    healthcheck:
      interval: 30s
      retries: 3
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      timeout: 10s
    image: wordpress:${WORDPRESS_VERSION}
    networks:
      - ah_network
    ports:
      - ${WORDPRESS_PORT}:80
    restart: unless-stopped
    volumes:
      - wordpress:/var/www/html
volumes:
  wordpress:
    driver: local
