networks:
  ah_network:
    driver: bridge
services:
  mysql:
    container_name: mysql
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
    expose:
      - ${MYSQL_PORT}
    healthcheck:
      interval: 30s
      retries: 3
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password=${MYSQL_ROOT_PASSWORD} || exit 1"]
      timeout: 10s
    image: mysql:${MYSQL_VERSION}
    networks:
      - ah_network
    restart: unless-stopped
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
    driver: local
